### ISSUE TITLE
Provisioning stub unit tests are having random failures at forked travis builds.

### ISSUE THREAD

**Issue by sasrin** [cloudfoundry-incubator/cf-abacus#106]
```
  abacus-provisioning-stub
    1) returns resource instance info by region/org/space/app/resource/plan/instance
    ✓ returns available resource configs (137ms)
    validating analytics  resource
        validated analytics  resource
    validating object-storage  resource
        validated object-storage  resource
    validating linux-container  resource
        validated linux-container  resource
    validating test-resource  resource
        validated test-resource  resource
    ✓ validates all test resource configurations (83ms)
    2) validates creation of new resource configurations
  2 passing (29s)
  2 failing
  1) abacus-provisioning-stub returns resource instance info by region/org/space/app/resource/plan/instance:
     Error: timeout of 20000ms exceeded. Ensure the done() callback is being called in this test.
  
  2) abacus-provisioning-stub validates creation of new resource configurations:
      Uncaught AssertionError: expected 8 to equal 3
      + expected - actual
      -8
      +3
      
      at cb (lib/test/test.js:55:41)
      at lib/test/test.js:100:9
      at /home/travis/build/sasrin/cf-abacus/node_modules/abacus-batch/lib/index.js:28:142
      at _.map._.collect (/home/travis/build/sasrin/cf-abacus/node_modules/underscore/underscore.js:172:24)
      at /home/travis/build/sasrin/cf-abacus/node_modules/abacus-batch/lib/index.js:28:8
      at /home/travis/build/sasrin/cf-abacus/node_modules/abacus-request/lib/index.js:66:293
      at /home/travis/build/sasrin/cf-abacus/node_modules/abacus-transform/lib/index.js:37:543
      at /home/travis/build/sasrin/cf-abacus/node_modules/abacus-request/lib/index.js:64:616
      at /home/travis/build/sasrin/cf-abacus/node_modules/abacus-transform/lib/index.js:34:222
      at _.map._.collect (/home/travis/build/sasrin/cf-abacus/node_modules/underscore/underscore.js:172:24)
      at Function.cbmap [as map] (/home/travis/build/sasrin/cf-abacus/node_modules/abacus-transform/lib/index.js:34:48)
      at /home/travis/build/sasrin/cf-abacus/node_modules/abacus-request/lib/index.js:64:80
      at /home/travis/build/sasrin/cf-abacus/node_modules/abacus-transform/lib/index.js:37:543
      at Object.callback (/home/travis/build/sasrin/cf-abacus/node_modules/abacus-request/lib/index.js:63:215)
      at Request._callback (/home/travis/build/sasrin/cf-abacus/node_modules/abacus-request/lib/index.js:44:351)
      at Request.self.callback (/home/travis/build/sasrin/cf-abacus/node_modules/abacus-request/node_modules/request/request.js:198:22)
      at Request.<anonymous> (/home/travis/build/sasrin/cf-abacus/node_modules/abacus-request/node_modules/request/request.js:1082:10)
      at IncomingMessage.<anonymous> (/home/travis/build/sasrin/cf-abacus/node_modules/abacus-request/node_modules/request/request.js:1009:12)
      at _stream_readable.js:944:16

```

**Comment by sasrin** [comment]
Also see this failure at our main travis build:

```
  abacus-provisioning-stub
    1) returns resource instance info by region/org/space/app/resource/plan/instance
    ✓ returns available resource configs (368ms)
    validating analytics  resource
        validated analytics  resource
    validating object-storage  resource
        validated object-storage  resource
    validating linux-container  resource
        validated linux-container  resource
    validating test-resource  resource
        validated test-resource  resource
    ✓ validates all test resource configurations (109ms)
    ✓ validates creation of new resource configurations (18838ms)
  3 passing (40s)
  1 failing
  1) abacus-provisioning-stub returns resource instance info by region/org/space/app/resource/plan/instance:
     Error: timeout of 20000ms exceeded. Ensure the done() callback is being called in this test.
  ```

**Comment by jsdelfino** [comment]
One of the issues is that the provisioning service uses a time-partitioned db for resource configs and runs range queries back to a time of 0 causing a ton of unnecessary database lookups.

The provisioning service doesn't need a time-partitioned db in the first place, so I'm going to change it to use a single-partition db.
