### ISSUE TITLE
Token validation fails when security is enabled. 

### ISSUE THREAD

**Issue by piotrprzybylski** [cloudfoundry-incubator/cf-abacus#107]
I configured abacus security by setting the following properties and tried to submit usage passing oauth token (with abacus.usage.write authority)

```
export TOKEN_SECRET=
export TOKEN_ALGORITHM=
export TOKEN_ENDPOINT=
 export CLIENT_ID=
export CLIENT_SECRET=
export SECURED=true 
```

The logs show the following
```
  abacus-oauth 60955 Validating OAuth bearer access token +0ms
  abacus-oauth 60955 Token validation failed { message: 'invalid signature',
  name: 'JsonWebTokenError',
  constructor: [Function] } - JsonWebTokenError: invalid signature
    at Object.JWT.verify (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-cfoauth/node_modules/jsonwebtoken/index.js:195:17)
    at validate (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-cfoauth/lib/index.js:100:23)
    at /Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-cfoauth/lib/index.js:122:7
    at Layer.handle [as handle_request] (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:312:13)
    at /Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:271:10)
    at /Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-vcapenv/lib/index.js:62:5
    at Layer.handle [as handle_request] (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:312:13)
    at /Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:271:10)
    at /Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-express/lib/index.js:284:5
    at Layer.handle [as handle_request] (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:312:13)
    at /Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:271:10)
    at /Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-express/lib/index.js:61:5
    at Layer.handle [as handle_request] (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:312:13)
    at /Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:271:10)
    at responseTime (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-express/node_modules/response-time/index.js:59:5)
    at Layer.handle [as handle_request] (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:312:13)
    at /Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:280:7 +0ms
  abacus-oauth 60955 OAuth bearer access token validation failed, invalid signature +1ms
```
However when I plug in the same token into modified test of the cfoauth module (with the same properties passed - secret and algorithm), the token is validated and the decoded form is returned.
```
describe.only('Valiate token', () => {

  it('Valid token', (done) => {

    const token = '...';
    // Test the validation
    oauth.validate(token, '...', '...',
      (err, val) => {
        console.log(err);
        console.log(JSON.stringify(val, null, '\t'));
        expect(err).to.equal(null);
        done();
      });
  });
});

```

**Comment by sasrin** [comment]
Environment variables needed to configure a secured Abacus are [Refer to manifest file at 1 as an example]:

*    **SECURED** -        'true' / 'false' -    Use 'true' to enable the security checks
*    **AUTHSERVER** -  Authorization Server URL  used to get access token endpoint in the format of "https://hostname:port" or just "https://hostname".
*   **CLIENTID** -  Client identifier registered with the specified authorization server.
*   **CLIENTSECRET** - Client secret used to authenticate the client identifier with the authorization server.
*   **JWTKEY** - Key used to sign the JWT- JWS
*  **JWTALGO** - Cryptographic algorithm used to sign and secure JWT-JWS



[1] https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/metering/collector/manifest.yml#L12-L17

**Comment by piotrprzybylski** [comment]
With the variables above, I got the following error
```
  abacus-oauth 62042 Error getting OAuth bearer access token, { message: 'Invalid URI "undefined/oauth/token?grant_type=client_credentials&scope=abacus.usage.write%20abacus.usage.read"' } - Error: Invalid URI "undefined/oauth/token?grant_type=client_credentials&scope=abacus.usage.write%20abacus.usage.read"
    at Request.init (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-request/node_modules/request/request.js:280:31)
    at new Request (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-request/node_modules/request/request.js:140:8)
    at request (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-request/node_modules/request/index.js:55:10)
    at /Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-request/node_modules/request/index.js:101:12
    at send (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-request/lib/index.js:148:5)
    at xrequest (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-request/lib/index.js:177:10)
    at /Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-request/lib/index.js:186:12
    at RetryOperation._fn (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-retry/lib/index.js:68:11)
    at RetryOperation.attempt (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-retry/node_modules/retry/lib/retry_operation.js:56:8)
    at wrapper (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-retry/lib/index.js:64:8)
    at newToken (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-cfoauth/lib/index.js:51:3)
    at /Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-cfoauth/lib/index.js:238:9
    at /Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-cfoauth/lib/index.js:42:5
    at Object.callback (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-retry/lib/index.js:84:9)
    at Request._callback (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-request/lib/index.js:165:16)
    at Request.self.callback (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-request/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-request/node_modules/request/request.js:1082:10)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/Users/piotrp/dev/oct/cf-abacus/node_modules/abacus-request/node_modules/request/request.js:1009:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11) +0ms
```

**Comment by sasrin** [comment]
> { message: 'Invalid URI "undefined/oauth/token?grant_type=client_credentials&scope=abacus.usage.write%20abacus.usage.read"' }

Possible reason could be that AUTHSERVER is not defined.

**Comment by piotrprzybylski** [comment]
It seems to be set correctly when this error happens. Could you please point me to the code where its used - grep only shows it in manifest files.

**Comment by jsdelfino** [comment]
Some references say: `authserver` in lowercase but the `abacus-urienv` module will resolve them using the AUTHSERVER env variable is set.

```
find . -name "*.js" | grep -v "node_modules" | grep "src" | xargs grep -il "AUTHSERVER"
./lib/aggregation/accumulator/src/index.js
./lib/aggregation/aggregator/src/index.js
./lib/aggregation/rate/src/index.js
./lib/aggregation/reporting/src/index.js
./lib/metering/collector/src/index.js
./lib/metering/meter/src/index.js
./lib/stubs/authserver/src/index.js
./lib/stubs/authserver/src/test/test.js
./lib/utils/cfoauth/src/index.js
```

**Comment by piotrprzybylski** [comment]
I believe I know what the problem was - the value set in the property AUTHSERVER should be the host name which will be able to respond to  GET /v2/info and return, among other values, 'token_endpoint'. If the host set in the AUTHSERVER property is the actual token endpoint, GET /v2/info returns 302 and token endpoint remains undefined. Once I set the property to point to api host, it is working. 

I think the unit test was passing since cfoauth can use a different env property API_HOST_NAME which was set to the right value (api host). 

Unless there is a component which assumes AUTHSERVER is actual token_endpoint, I don't think there is a problem with the code, perhaps the name is a little misleading.

**Comment by sasrin** [comment]
Tried with AUTHSERVER=https://uaa.ng.bluemix.net and got HTTP response code 200 - with a different response body. Did you get 302 or 200? could you check it out and confirm?

```
  abacus-oauth 63158 Getting OAuth bearer access token +2m
  abacus-oauth 63158 Retrieving token endpoint information from authorization server, 'https://uaa.ng.bluemix.net' +0ms  

200  - { timestamp: '2015-06-12T17:38:10-0400',
  app: { version: '2.3.0' },
  idpDefinitions: [],
  fieldUsernameShow: true,
  zone_name: 'uaa',
  commit_id: 'git-metadata-not-found',
  prompts: 
   { username: [ 'text', 'Email' ],
     password: [ 'password', 'Password' ],
     passcode: 
      [ 'password',
        'One Time Code (Get one at https://uaa.ng.bluemix.net/passcode)' ] },
  forgotPasswordLink: 'https://console.run.pivotal.io/password_resets/new',
  createAccountLink: 'https://console.run.pivotal.io/register',
  links: 
   { register: 'https://console.run.pivotal.io/register',
     passwd: 'https://console.run.pivotal.io/password_resets/new',
     login: 'https://login.ng.bluemix.net',
     uaa: 'https://uaa.ng.bluemix.net' },
  entityID: 'login.ng.bluemix.net' } { 'x-backside-transport': 'OK OK',
  connection: 'Keep-Alive',
  'transfer-encoding': 'chunked',
  'access-control-allow-origin': '*',
  'cache-control': 'no-cache, no-store, max-age=0, must-revalidate,no-cache, no-store, max-age=0',
  'content-language': 'en-US',
  'content-type': 'application/json;charset=UTF-8',
  date: 'Thu, 22 Oct 2015 03:39:07 GMT',
  expires: '0,Thu, 01 Jan 1970 00:00:00 GMT',
  pragma: 'no-cache,no-cache',
  server: 'Apache-Coyote/1.1',
  'x-cf-requestid': '140c0aa2-13a8-4e56-5b03-8d05e6cd21c0',
  'x-content-type-options': 'nosniff',
  'x-frame-options': 'DENY',
  'x-xss-protection': '1; mode=block',
  'x-client-ip': '76.247.188.141',
  'x-global-transaction-id': '368704557' }
  abacus-oauth 63158 Retrieved undefined +287ms
  abacus-oauth 63158 Retrieving token from access token endpoint, undefined +0ms
  e-abacus-request 63158 Request error { message: 'Invalid URI "undefined/oauth/token?grant_type=client_credentials&scope=abacus.usage.write%20abacus.usage.read"' } - Error: Invalid URI "undefined/oauth/token?grant_type=client_credentials&scope=abacus.usage.write%20abacus.usage.read"

```

**Comment by jsdelfino** [comment]
@piotrprzybylski, @sasrin, is that issue resolved?

**Comment by jsdelfino** [comment]
I've fixed the variable names: CLIENT_SECRET, CLIENT_ID and AUTH_SERVER (all with underscores, like @piotrprzybylski originally had in the cfoauth module). See issue #119 for more details.

**Comment by jsdelfino** [comment]
@sasrin is also going to add a check to return a clearer error if the auth server is not returning a token endpoint.

**Comment by piotrprzybylski** [comment]
So to clarify - the value set in the AUTH_SERVER variable must point to the host which will return ```token_endpoint``` from the ```GET /v2/info ```

**Comment by jsdelfino** [comment]
Correct
