### ISSUE TITLE
data-flow test fails in Travis

### ISSUE THREAD

**Issue by hsiliev** [cloudfoundry-incubator/cf-abacus#118]
Dataflow test fails in Travis. For example: https://travis-ci.org/cloudfoundry-incubator/cf-abacus/jobs/87044363

```
  abacus-dataflow

    ✓ runs a map transform and stores its inputs and outputs (798ms)

    1) runs a reduce transform and stores its inputs and outputs

  1 passing (2s)

  1 failing

  1) abacus-dataflow runs a reduce transform and stores its inputs and outputs:

      Uncaught AssertionError: expected { t: 1443650828619, x: 3, val: 4 } to deeply equal { t: 1443650828618, x: 2, val: 2 }

      + expected - actual

       {

      -  "t": 1443650828619

      -  "val": 4

      -  "x": 3

      +  "t": 1443650828618

      +  "val": 2

      +  "x": 2

       }

      

      at Assertion.assertEqual (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-mocha/node_modules/chai/lib/chai/core/assertions.js:468:19)

      at Assertion.ctx.(anonymous function) [as equal] (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-mocha/node_modules/chai/lib/chai/utils/addMethod.js:40:25)

      at postspy (lib/test/test.js:361:68)

      at Object.batch_post (lib/test/test.js:37:12)

      at flush [as _onTimeout] (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-batch/lib/index.js:27:116)

/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-mocha/node_modules/chai/lib/chai/assertion.js:107

      throw new AssertionError(msg, {

            ^

AssertionError: expected { t: 1443650828620, x: 4, val: 4 } to deeply equal { t: 1443650828618, x: 2, val: 2 }

    at Assertion.assertEqual (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-mocha/node_modules/chai/lib/chai/core/assertions.js:468:19)

    at Assertion.ctx.(anonymous function) [as equal] (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-mocha/node_modules/chai/lib/chai/utils/addMethod.js:40:25)

    at postspy (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-dataflow/lib/test/test.js:361:68)

    at Object.batch_post (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-dataflow/lib/test/test.js:37:12)

    at flush [as _onTimeout] (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-batch/lib/index.js:27:116)

    at Timer.listOnTimeout (timers.js:119:15)

npm ERR! Test failed.  See above for more details.
```

**Comment by jsdelfino** [comment]
The problem is that the test logic in the postspy function is not deterministic as documents can be processed out of order (and that's OK). I'm going to fix this by keeping track of the expected docs using their post time (t field) instead of the order in which they were posted.

**Comment by jsdelfino** [comment]
Well, it looks like the approach I described won't work either when events get processed out of order, so the solution is probably to look to the final result once all the events have been processed. I'll work on that change later today or monday, after I cut the 0.0.2-rc.2 release.
