### ISSUE TITLE
Unable to start apps

### ISSUE THREAD

**Issue by rajkiranrbala** [cloudfoundry-incubator/cf-abacus#142]
I am unable to start the apps after building.
https://github.com/cloudfoundry-incubator/cf-abacus/commit/a7793c61772129a9069980439aa0d585f6b1c80f
```sh
$ npm run build
...

Coverage lines 82.93% statements 82.93% src/index.js

Run time 1071ms


Overall coverage lines 93.1% statements 92.43%s

$ npm run start

> cf-abacus@0.0.2 start /Users/rajkiranrbala/workspace/cf-abacus
> bin/start

/Users/rajkiranrbala/workspace/cf-abacus/node_modules/abacus-etc/src/apprc.js:18
var parse = (content) => {
                      ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/rajkiranrbala/workspace/cf-abacus/node_modules/abacus-etc/apprc:5:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

$ node -v
v0.12.7

$ npm -v
2.11.3
```

**Comment by sasrin** [comment]
Use ES5 to define variables and functions at abacus-etc
Fixes 142.
