### ISSUE TITLE
Abacus usage collector crashes under high load

### ISSUE THREAD

**Issue by hsiliev** [cloudfoundry-incubator/cf-abacus#171]
cf-bridge with around 200000 events (#166) causes the usage collector to crash. One of the crashes shows OOM:

```
± |master U:2 ?:3 ✗| → cf events abacus-usage-collector
Getting events for app abacus-usage-collector in org abacus / space abacus as i024099...

time                          event                 actor                    description
2015-11-15T03:22:35.00+0200   app.crash             abacus-usage-collector   index: 5, reason: CRASHED, exit_description: app instance exited, exit_status: 0
2015-11-15T03:02:34.00+0200   app.crash             abacus-usage-collector   index: 2, reason: CRASHED, exit_description: failed to start, exit_status: -1
2015-11-14T14:45:01.00+0200   app.crash             abacus-usage-collector   index: 1, reason: CRASHED, exit_description: failed to start, exit_status: -1
2015-11-14T14:44:43.00+0200   app.crash             abacus-usage-collector   index: 1, reason: CRASHED, exit_description: app instance exited, exit_status: 0
2015-11-14T10:05:44.00+0200   app.crash             abacus-usage-collector   index: 0, reason: CRASHED, exit_description: app instance exited, exit_status: 0
2015-11-14T09:47:11.00+0200   app.crash             abacus-usage-collector   index: 2, reason: CRASHED, exit_description: app instance exited, exit_status: 0
2015-11-14T09:35:09.00+0200   app.crash             abacus-usage-collector   index: 1, reason: CRASHED, exit_description: out of memory, exit_status: 255
2015-11-14T09:31:03.00+0200   app.crash             abacus-usage-collector   index: 3, reason: CRASHED, exit_description: app instance exited, exit_status: 0
2015-11-14T09:23:00.00+0200   app.crash             abacus-usage-collector   index: 4, reason: CRASHED, exit_description: app instance exited, exit_status: 0
2015-11-13T16:01:06.00+0200   app.crash             abacus-usage-collector   index: 1, reason: CRASHED, exit_description: failed to start, exit_status: -1
2015-11-13T15:58:34.00+0200   audit.app.update      i024099                  state: STARTED
2015-11-13T15:56:03.00+0200   audit.app.update      i024099
2015-11-13T15:56:03.00+0200   audit.app.map-route   i024099
2015-11-13T15:56:01.00+0200   audit.app.create      i024099                  disk_quota: 512, instances: 6, memory: 512, state: STOPPED, environment_json: PRIVATE DATA HIDDEN
```

Using PouchDB, which causes a lot of errors in the usage collector:
```
2015-11-16T10:29:44.73+0200 [App/1]      OUT 2015-11-16T08:29:44.732Z e-abacus-dataflow 1141 Error processing input doc t/0001447662516550-0-1-120-0/k/anonymous, { message: 'ETIMEDOUT', status: 400 } - Error: ETIMEDOUT
2015-11-16T10:29:44.73+0200 [App/1]      OUT     at onError (/home/vcap/app/node_modules/pouchdb/lib/deps/ajax/ajaxCore.js:53:18)
2015-11-16T10:29:44.73+0200 [App/1]      OUT     at Request.emit (events.js:107:17)
2015-11-16T10:29:44.73+0200 [App/1]      OUT     at null._onTimeout (/home/vcap/app/node_modules/request/request.js:811:12)
2015-11-16T10:29:44.73+0200 [App/1]      OUT     at Timer.listOnTimeout (timers.js:110:15)
2015-11-16T10:29:45.10+0200 [App/2]      OUT 2015-11-16T08:29:45.106Z e-abacus-retry 1171 Function dbclient.wrapper calling back with error { message: 'Function dbclient.wrapper failed-fast due to open circuit-breaker' } - Error: Function dbclient.wrapper failed-fast due to open circuit-breaker
2015-11-16T10:29:45.10+0200 [App/2]      OUT     at Error.CircuitBreakerError (/home/vcap/app/node_modules/abacus-breaker/lib/index.js:58:9)
2015-11-16T10:29:45.10+0200 [App/2]      OUT     at callback (/home/vcap/app/node_modules/abacus-breaker/lib/index.js:71:81)
2015-11-16T10:29:45.10+0200 [App/2]      OUT     at Object.wrapper [as put] (/home/vcap/app/node_modules/abacus-breaker/lib/index.js:177:12)
2015-11-16T10:29:45.10+0200 [App/2]      OUT     at RetryOperation._fn (/home/vcap/app/node_modules/abacus-retry/lib/index.js:69:11)
2015-11-16T10:29:45.10+0200 [App/2]      OUT     at null._onTimeout (/home/vcap/app/node_modules/retry/lib/retry_operation.js:32:10)
2015-11-16T10:29:45.10+0200 [App/2]      OUT     at Timer.listOnTimeout (timers.js:110:15)
2015-11-16T10:29:45.10+0200 [App/2]      OUT 2015-11-16T08:29:45.108Z e-abacus-router 1171 Route error - generator error - { message: 'ETIMEDOUT', status: 400 } - Error: ETIMEDOUT
2015-11-16T10:29:45.10+0200 [App/2]      OUT     at onError (/home/vcap/app/node_modules/pouchdb/lib/deps/ajax/ajaxCore.js:53:18)
2015-11-16T10:29:45.10+0200 [App/2]      OUT     at Request._callback (/home/vcap/app/node_modules/pouchdb/lib/deps/ajax/ajaxCore.js:103:14)
2015-11-16T10:29:45.10+0200 [App/2]      OUT     at self.callback (/home/vcap/app/node_modules/request/request.js:198:22)
2015-11-16T10:29:45.10+0200 [App/2]      OUT     at Request.emit (events.js:107:17)
2015-11-16T10:29:45.10+0200 [App/2]      OUT     at null._onTimeout (/home/vcap/app/node_modules/request/request.js:811:12)
2015-11-16T10:29:45.10+0200 [App/2]      OUT     at Timer.listOnTimeout (timers.js:110:15)
```

**Comment by jsdelfino** [comment]
See my comments in #168. I think that most of the issues I described there apply here too (except for the part about making the aggregated/rated usage documents smaller).

**Comment by jsdelfino** [comment]
With commit c41804c providing a back pressure mechanism, throttling of 1000 concurrent requests per instance, the various memory leak and tuning fixes from the last two weeks and a CouchDB or Cloudant DB, I'm now able run sustained loads again without seeing these crashes. PouchDB still crashes around 1GB of data but that's expected as it's not meant to be used as a production DB. Please re-open the issue if you still see these issues in your environment with the latest version. Thanks.
