### ISSUE TITLE
Travis build fails with: LRU: key must be a string or number.

### ISSUE THREAD

**Issue by hsiliev** [cloudfoundry-incubator/cf-abacus#214]
Travis [build](https://travis-ci.org/cloudfoundry-incubator/cf-abacus/jobs/105123589) fails on **abacus-usage-meter-itest** with the following error in the [logs](https://api.travis-ci.org/jobs/105123589/log.txt?deansi=true):
```
TypeError: LRU: key must be a string or number. Almost certainly a bug! undefined
    at typeCheckKey (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/lru-cache/lib/lru-cache.js:20:19)
    at LRUCache.get (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/lru-cache/lib/lru-cache.js:230:3)
    at Object.get (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-lrucache/lib/index.js:45:20)
    at cached (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-metering-config/lib/index.js:104:18)
    at /home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-metering-config/lib/index.js:121:13
    at /home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-lock/lib/index.js:16:5
    at lock (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/lock/index.js:69:7)
    at lockcb (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-lock/lib/index.js:14:3)
    at config (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-metering-config/lib/index.js:116:3)
    at /home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/thunkify/index.js:43:12
    at next (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/co/index.js:90:21)
    at /home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/co/index.js:45:5
    at next (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/co/index.js:90:21)
    at /home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/co/index.js:45:5
    at next (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/co/index.js:90:21)
    at /home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/co/index.js:93:18
    at Immediate._onImmediate (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/co/index.js:52:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by hsiliev** [comment]
Abacus is building ok locally with:
```
$ etc/versions
OS Darwin SOFM33790380A 15.2.0 x64
Node v5.4.1
Npm 3.3.12
```

**Comment by jsdelfino** [comment]
Looks like this is now fixed. The build was broken for some time as we were in the middle of refactoring the Abacus stubs/plugins.
