### ISSUE TITLE
Large size Abacus fails to generate report with mongoclient

### ISSUE THREAD

**Issue by hsiliev** [cloudfoundry-incubator/cf-abacus#238]
Default size Abacus works fine, but when deployed on CF with large the reporting fails with:
```
2016-02-16T14:13:51.91+0200 [App/5]      OUT >>>>>>>>>>>>>>>>>>>>>>>>>>>> [ { error: 'not_found' }, [length]: 1 ]
2016-02-16T14:13:51.91+0200 [App/5]      OUT 2016-02-16T12:13:51.915Z e-abacus-router 52 Route error - generator error - { message: 'Cannot read property \'_id\' of undefined' } - TypeError: Cannot read property '_id' of undefined
2016-02-16T14:13:51.91+0200 [App/5]      OUT     at /home/vcap/app/lib/index.js:614:35
2016-02-16T14:13:51.91+0200 [App/5]      OUT     at /home/vcap/app/node_modules/underscore/underscore.js:227:11
2016-02-16T14:13:51.91+0200 [App/5]      OUT     at Function._.each._.forEach (/home/vcap/app/node_modules/underscore/underscore.js:153:9)
2016-02-16T14:13:51.91+0200 [App/5]      OUT     at _.filter._.select (/home/vcap/app/node_modules/underscore/underscore.js:226:7)
2016-02-16T14:13:51.91+0200 [App/5]      OUT     at /home/vcap/app/lib/index.js:613:34
2016-02-16T14:13:51.91+0200 [App/5]      OUT     at _.map._.collect (/home/vcap/app/node_modules/underscore/underscore.js:172:24)
2016-02-16T14:13:51.91+0200 [App/5]      OUT     at /home/vcap/app/lib/index.js:612:28
2016-02-16T14:13:51.91+0200 [App/5]      OUT     at _.map._.collect (/home/vcap/app/node_modules/underscore/underscore.js:172:24)
2016-02-16T14:13:51.91+0200 [App/5]      OUT     at consumerUsage$ (/home/vcap/app/lib/index.js:610:21)
2016-02-16T14:13:51.91+0200 [App/5]      OUT     at tryCatch (/home/vcap/app/node_modules/babel-regenerator-runtime/runtime.js:61:40)
2016-02-16T14:13:51.91+0200 [App/5]      OUT     at GeneratorFunctionPrototype.invoke [as _invoke] (/home/vcap/app/node_modules/babel-regenerator-runtime/runtime.js:329:22)
2016-02-16T14:13:51.91+0200 [App/5]      OUT     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/vcap/app/node_modules/babel-regenerator-runtime/runtime.js:94:21)
2016-02-16T14:13:51.91+0200 [App/5]      OUT     at next (/home/vcap/app/node_modules/co/index.js:74:21)
2016-02-16T14:13:51.91+0200 [App/5]      OUT     at /home/vcap/app/node_modules/co/index.js:93:18
2016-02-16T14:13:51.91+0200 [App/5]      OUT     at Immediate._onImmediate (/home/vcap/app/node_modules/co/index.js:52:14)
2016-02-16T14:13:51.91+0200 [App/5]      OUT     at processImmediate [as _immediateCallback] (timers.js:383:17)
2016-02-16T14:13:51.92+0200 [RTR/0]      OUT abacus-usage-reporting.cfapps.sap.hana.ondemand.com - [16/02/2016:12:13:51 +0000] "GET /v1/metering/organizations/us-south:a3d7fe4d-3cb1-4cc3-a831-ffe98e20cf27/aggregated/usage HTTP/1.1" 500 0 51 "-" "-" 192.168.0.106:52043 x_forwarded_for:"172.18.74.8" x_forwarded_proto:"https" vcap_request_id:af034bbd-0191-4c65-6f37-9d95326385b5 response_time:0.366768249 app_id:50f9d178-1fa7-41f8-946d-580d1d0d70ec
```

We added dumps after https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/aggregation/reporting/src/index.js#L358-L359, to list the consumers which are `not_found`. 

The `consumerUsage` function has to error handling, so the code tries to get _id from non-existing document, resulting in the error above. The client in turn gets 500 response code.

**Comment by hsiliev** [comment]
Seems the problem is cause by wrong partition for the aggregated data. Aggregator tries to access `abacus-aggregator-aggregated-usage-5-201602`, while the data is in `abacus-aggregator-aggregated-usage-4-201602`
