### ISSUE TITLE
usage-report tests fail with persistent DB

### ISSUE THREAD

**Issue by hsiliev** [cloudfoundry-incubator/cf-abacus#256]
The tests are running fine with PouchDB (https://travis-ci.org/cloudfoundry-incubator/cf-abacus/builds/112531475). However they error when running them with persistent DB like Couch or Mongo:

Couch:
```
 abacus-usage-report
    when rated usage contains small numbers
      ✓ retrieves rated usage for an organization (4622ms)
      ✓ queries rated usage for an organization (181ms)
      ✓ queries rated usage using GraphQL queries (237ms)
    when rated usage contains big numbers
      ✓ retrieves rated usage with 16 significant digits (109ms)
    when rated usage contains a slack
      1) checks that time-based resource uses its bounds
    when accumulated usage has small numbers
      ✓ Retrieve accumulated usage using a GraphQL query (45ms)
    when querying complex usage with graphql
      - Retrieve accumulated usage using a GraphQL query


  5 passing (6s)
  1 pending
  1 failing

  1) abacus-usage-report when rated usage contains a slack checks that time-based resource uses its bounds:
     Uncaught TypeError: Cannot read property 'resources' of undefined
      at Object.callback (lib/test/test.js:1903:49)
      at /Users/development/workspace/cf-abacus/node_modules/abacus-request/lib/index.js:46:120
      at Request._callback (/Users/development/workspace/cf-abacus/node_modules/abacus-request/lib/index.js:43:215)
      at Request.self.callback (/Users/development/workspace/cf-abacus/node_modules/abacus-request/node_modules/request/request.js:199:22)
      at Request.<anonymous> (/Users/development/workspace/cf-abacus/node_modules/abacus-request/node_modules/request/request.js:1036:10)
      at IncomingMessage.<anonymous> (/Users/development/workspace/cf-abacus/node_modules/abacus-request/node_modules/request/request.js:963:12)
      at endReadableNT (_stream_readable.js:905:12)
```

Mongo:
```
  abacus-usage-report
    when rated usage contains small numbers
      ✓ retrieves rated usage for an organization (523ms)
      ✓ queries rated usage for an organization (157ms)
      ✓ queries rated usage using GraphQL queries (243ms)
    when rated usage contains big numbers
      ✓ retrieves rated usage with 16 significant digits (110ms)
    when rated usage contains a slack
      1) checks that time-based resource uses its bounds
    when accumulated usage has small numbers
      ✓ Retrieve accumulated usage using a GraphQL query (48ms)
    when querying complex usage with graphql
      - Retrieve accumulated usage using a GraphQL query


  5 passing (2s)
  1 pending
  1 failing

  1) abacus-usage-report when rated usage contains a slack checks that time-based resource uses its bounds:
     Uncaught TypeError: Cannot read property 'resources' of undefined
      at Object.callback (lib/test/test.js:1903:49)
      at /tmp/build/b2d53b74/abacus/node_modules/abacus-request/lib/index.js:46:120
      at Request._callback (/tmp/build/b2d53b74/abacus/node_modules/abacus-request/lib/index.js:43:215)
      at Request.self.callback (/tmp/build/b2d53b74/abacus/node_modules/request/request.js:199:22)
      at Request.<anonymous> (/tmp/build/b2d53b74/abacus/node_modules/request/request.js:1036:10)
      at IncomingMessage.<anonymous> (/tmp/build/b2d53b74/abacus/node_modules/request/request.js:963:12)
      at endReadableNT (_stream_readable.js:905:12)
```

**Comment by KRuelY** [comment]
This happens because the unit tests are running concurrently. Unlike in-memory db, the data in the  mongo/couch db are persisted after each test. The unit tests assume that the db is clean before the tests are running, but that is not the case when we run build/rebuild with mongo/couch. The report test fails because there are matching data from the aggregator test.

This can be avoided by making the organization_ids in the unit tests to be different: 3080c0c6995452fef8587c9a3fea4dde7d0f7057.
