### ISSUE TITLE
"Can't set headers after they are sent" on duplicate submission

### ISSUE THREAD

**Issue by hsiliev** [cloudfoundry-incubator/cf-abacus#281]
The error from the generator causes several chained errors since the headers cannot be modified (response already sent?)
```
2016-03-24T09:42:05.003Z e-abacus-router 14574 Route error - generator error - { message: 'Duplicate document update conflict',
  id: 'k/e8139b76-e829-4af3-b332-87316b1c0a6c/35c4ff2f/UNKNOWN/basic/t/0001458812464523/0001458812464523',
  status: 409,
  error: 'conflict',
  reason: 'Duplicate document update conflict',
  noretry: true,
  nobreaker: true } - Error: Duplicate document update conflict
    at dupInput (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/abacus-dataflow/lib/index.js:133:16)
    at _callee$ (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/abacus-dataflow/lib/index.js:205:54)
    at tryCatch (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/babel-regenerator-runtime/runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/babel-regenerator-runtime/runtime.js:329:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/babel-regenerator-runtime/runtime.js:94:21)
    at next (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/co/index.js:74:21)
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/co/index.js:45:5
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/abacus-transform/lib/index.js:83:5
    at _.map._.collect (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/underscore/underscore.js:172:24)
    at cbmap (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/abacus-transform/lib/index.js:81:3)
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/thunkify/index.js:43:12
    at next (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/co/index.js:90:21)
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/co/index.js:45:5
    at next (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/co/index.js:90:21)
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/co/index.js:45:5
    at next (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/co/index.js:90:21)
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/co/index.js:45:5
    at next (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/co/index.js:90:21)
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/co/index.js:45:5
    at run (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/abacus-throttle/lib/index.js:40:18)
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/abacus-throttle/lib/index.js:78:12
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/abacus-router/lib/index.js:54:13
    at Layer.handle [as handle_request] (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/layer.js:95:5)
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:271:10)
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/abacus-router/lib/index.js:124:5
2016-03-24T09:42:05.004Z e-abacus-express 14574 Middleware error { message: 'Duplicate document update conflict',
  id: 'k/e8139b76-e829-4af3-b332-87316b1c0a6c/35c4ff2f/UNKNOWN/basic/t/0001458812464523/0001458812464523',
  status: 409,
  error: 'conflict',
  reason: 'Duplicate document update conflict',
  noretry: true,
  nobreaker: true } - Error: Duplicate document update conflict
    at dupInput (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/abacus-dataflow/lib/index.js:133:16)
    at _callee$ (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/abacus-dataflow/lib/index.js:205:54)
    at tryCatch (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/babel-regenerator-runtime/runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/babel-regenerator-runtime/runtime.js:329:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/babel-regenerator-runtime/runtime.js:94:21)
    at next (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/co/index.js:74:21)
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/co/index.js:45:5
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/abacus-transform/lib/index.js:83:5
    at _.map._.collect (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/underscore/underscore.js:172:24)
    at cbmap (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/abacus-transform/lib/index.js:81:3)
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/thunkify/index.js:43:12
    at next (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/co/index.js:90:21)
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/co/index.js:45:5
    at next (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/co/index.js:90:21)
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/co/index.js:45:5
    at next (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/co/index.js:90:21)
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/co/index.js:45:5
    at next (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/co/index.js:90:21)
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/co/index.js:45:5
    at run (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/abacus-throttle/lib/index.js:40:18)
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/abacus-throttle/lib/index.js:78:12
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/abacus-router/lib/index.js:54:13
    at Layer.handle [as handle_request] (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/layer.js:95:5)
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:271:10)
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/abacus-router/lib/index.js:124:5
2016-03-24T09:42:05.005Z e-abacus-express 14574 Middleware error { message: 'Can\'t set headers after they are sent.' } - Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at ServerResponse.header (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/response.js:718:10)
    at ServerResponse.send (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/response.js:163:12)
    at ServerResponse.json (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/response.js:249:15)
    at ServerResponse.send (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/response.js:151:21)
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/abacus-express/lib/index.js:503:21
    at Layer.handle [as handle_request] (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:312:13)
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:271:10)
    at serveStatic (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/serve-static/index.js:74:16)
    at Layer.handle [as handle_request] (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:312:13)
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:271:10)
    at serveStatic (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/serve-static/index.js:74:16)
    at Layer.handle [as handle_request] (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:312:13)
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:271:10)
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/abacus-express/lib/index.js:74:62
    at Layer.handle [as handle_request] (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:312:13)
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:271:10)
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/abacus-express/lib/index.js:265:7
2016-03-24T09:42:05.005Z e-abacus-express 14574 Exception sending error { message: 'Can\'t set headers after they are sent.' } - Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at ServerResponse.header (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/response.js:718:10)
    at ServerResponse.send (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/response.js:163:12)
    at ServerResponse.json (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/response.js:249:15)
    at ServerResponse.send (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/response.js:151:21)
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/abacus-express/lib/index.js:378:55
    at Layer.handle_error (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:310:13)
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:271:10)
    at Layer.handle [as handle_request] (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/layer.js:97:5)
    at trim_prefix (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:312:13)
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:271:10)
    at serveStatic (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/serve-static/index.js:74:16)
    at Layer.handle [as handle_request] (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:312:13)
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:271:10)
    at serveStatic (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/serve-static/index.js:74:16)
    at Layer.handle [as handle_request] (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:312:13)
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/index.js:271:10)
    at /Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/abacus-express/lib/index.js:74:62
    at Layer.handle [as handle_request] (/Users/development/workspace/cf-abacus/test/cf/bridge/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by jsdelfino** [comment]
Fixed in 90459da.
