### ISSUE TITLE
abacus-mongoclient tests fail with node 6.2.0

### ISSUE THREAD

**Issue by hsiliev** [cloudfoundry-incubator/cf-abacus#327]
Tests run fine with node 5.11.1 and fail with 6.2.0

```
1) abacus-mongoclient supports self-signed certificates for SSL:
     Error: done() called multiple times
      at Suite.<anonymous> (lib/test/test.js:1673:3)
      at Object.<anonymous> (lib/test/test.js:25:1)
      at Object.Module._extensions.(anonymous function) [as .js] (/workspace/Develop/cf-abacus/node_modules/istanbul/lib/hook.js:109:37)
      at require (internal/module.js:20:19)
      at Array.forEach (native)
      at Object.runCLI (/workspace/Develop/cf-abacus/node_modules/abacus-mocha/src/index.js:206:9)
      at Object.<anonymous> (/workspace/Develop/cf-abacus/node_modules/abacus-mocha/mocha:5:27)
      at node.js:449:3
```

**Comment by hsiliev** [comment]
With node.js >=6 we get two `clientError` events with mongo driver. Tried to downgrade the driver, but that did not produce different results.

Changed the test to start the checks after server is started and then to remove listeners and stop test server.
