### ISSUE TITLE
Dataflow tests fail on MongoDB

### ISSUE THREAD

**Issue by hsiliev** [cloudfoundry-incubator/cf-abacus#347]
The tests fail with:
```
Testing...

  abacus-dataflow
    dataflow map
      ✓ runs a map transform and stores its inputs and outputs (909ms)
      ✓ does not store map outputs when error exists (829ms)
      ✓ propagates mapper error from the sink and does not store to output (915ms)
      ✓ stores map errors to error db (888ms)
      ✓ removes mapper error docs from db (306ms)
    dataflow reducer
      ✓ runs a reduce transform and stores its inputs and outputs (806ms)
      1) runs a reduce transform and down samples outputs
      ✓ does not store reduce outputs when error exists (457ms)
      ✓ propagates reducer error from the sink and does not store to output (560ms)
      ✓ does batch post, and gather the errors (256ms)
      ✓ stores reducer errors to error db (562ms)
      ✓ removes reducer errors docs from db (258ms)


  11 passing (7s)
  1 failing

  1) abacus-dataflow dataflow reducer runs a reduce transform and down samples outputs:

      Uncaught AssertionError: expected 409 to equal 201
      + expected - actual

      -409
      +201

      at lib/test/test.js:1444:40
      at Request._callback (/Users/development/workspace/cf-abacus/node_modules/abacus-request/lib/index.js:167:14)
      at Request.self.callback (/Users/development/workspace/cf-abacus/node_modules/request/request.js:200:22)
      at Request.<anonymous> (/Users/development/workspace/cf-abacus/node_modules/request/request.js:1067:10)
      at IncomingMessage.<anonymous> (/Users/development/workspace/cf-abacus/node_modules/request/request.js:988:12)
      at endReadableNT (_stream_readable.js:913:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by hsiliev** [comment]
Reverting 15e1e1776016030bf2e953ca2d415cf15222a3f0 solves the problem.

**Comment by jsdelfino** [comment]
@hsiliev: I just submitted pull request #348 to fix this issue. Could you guys please review and see if these changes will work for you too, without introducing any other issues in your MongoDB deployments? Thanks!
