### ISSUE TITLE
Dataflow tests fail on Travis with MongoDB

### ISSUE THREAD

**Issue by hsiliev** [cloudfoundry-incubator/cf-abacus#399]
Tests in https://travis-ci.org/cloudfoundry-incubator/cf-abacus/jobs/153122940 fail with:
```
 abacus-dataflow

    dataflow map

      ✓ runs a map transform and stores its inputs and outputs (826ms)

      ✓ Save to output db when it gets duplicate(409) (465ms)

      ✓ does not store map outputs when error exists (432ms)

      ✓ propagates mapper error from the sink and does not store to output (532ms)

      ✓ stores map errors to error db (602ms)

      ✓ removes mapper error docs from db (271ms)

    dataflow reducer

      ✓ runs a reduce transform and stores its inputs and outputs (906ms)

      ✓ runs a reduce transform and stores its inputs and outputs (564ms)

      ✓ runs a reduce transform and down samples outputs (821ms)

      ✓ does not store reduce outputs when error exists (384ms)

      ✓ propagates reducer error from the sink and does not store to output (561ms)

      ✓ does batch post, and gather the errors (223ms)

      1) stores reducer errors to error db

      2) removes reducer errors docs from db

  12 passing (7s)

  2 failing

  1) abacus-dataflow dataflow reducer stores reducer errors to error db:

      Uncaught AssertionError: expected 0 to equal 1

      + expected - actual

      -0

      +1

      

      at lib/test/test.js:2770:44

      at Request._callback (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-request/lib/index.js:45:215)

      at Request.self.callback (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/request/request.js:187:22)

      at Request.<anonymous> (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/request/request.js:1044:10)

      at IncomingMessage.<anonymous> (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/request/request.js:965:12)

      at endReadableNT (_stream_readable.js:926:12)

      at _combinedTickCallback (internal/process/next_tick.js:74:11)

      at process._tickCallback (internal/process/next_tick.js:98:9)

  2) abacus-dataflow dataflow reducer removes reducer errors docs from db:

      Uncaught AssertionError: expected 404 to equal 200

      + expected - actual

      -404

      +200

      

      at lib/test/test.js:2786:41

      at Request._callback (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-request/lib/index.js:45:215)

      at Request.self.callback (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/request/request.js:187:22)

      at Request.<anonymous> (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/request/request.js:1044:10)

      at IncomingMessage.<anonymous> (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/request/request.js:965:12)

      at endReadableNT (_stream_readable.js:926:12)

      at _combinedTickCallback (internal/process/next_tick.js:74:11)

      at process._tickCallback (internal/process/next_tick.js:98:9)

```

**Comment by hsiliev** [comment]
Local build on Mac with Mongo 3 and on Linux with Mongo 2.6 are running fine.

Seems the problem is with Travis build only. Since we tried with older Mongo I guess we can rule out the DB version. 

We could not reproduce the problem by loading the CPU/disk of the local machine.

**Comment by hsiliev** [comment]
Dataflow tests with Mongo on Travis seem to run fine in isolation:
https://travis-ci.org/cloudfoundry-incubator/cf-abacus/builds/153248417

**Comment by hsiliev** [comment]
Investigating a possible connection between mongoclient tests, Mongo and dataflow tests

**Comment by hsiliev** [comment]
Disabling a single test - "exact order" allows dataflow to pass. I made experiments with deleting the mongo test data after the test and adding cooldown to the test, but this did not help.

Seems like Mongo does not function correctly after the exact order test.

**Comment by hsiliev** [comment]
Changing the partitioning function in "exact order" test made the tests pass.

**Comment by hsiliev** [comment]
Fixed with https://github.com/cloudfoundry-incubator/cf-abacus/commit/3f6ab7dd4a2b8fec2fee128dd97c01dc5a80a237

Using nvm and non-node container seems to be causing lots of problems with Mongo.
