### ISSUE TITLE
abacus-usage-collector tests fail with MongoDB

### ISSUE THREAD

**Issue by hsiliev** [cloudfoundry-incubator/cf-abacus#413]
abacus-usage-collector-itest times out on Travis
Unit tests fail on Linux/Mongo 2.6 and Mac/Mongo 3.2.

Logs from Mac's run:
```
  1) abacus-usage-collector returns error doc due to pricing plan not found:
     Uncaught AssertionError: expected [Error: connection 1871 to localhost:27017 closed] to equal undefined
      at lib/test/test.js:737:26
      at /Users/hsiliev/workspace/cf-abacus/node_modules/abacus-batch/lib/index.js:87:30
      at _.map._.collect (/Users/hsiliev/workspace/cf-abacus/node_modules/underscore/underscore.js:172:24)
      at /Users/hsiliev/workspace/cf-abacus/node_modules/abacus-batch/lib/index.js:84:14
      at /Users/hsiliev/workspace/cf-abacus/node_modules/abacus-request/lib/index.js:341:11
      at /Users/hsiliev/workspace/cf-abacus/node_modules/abacus-transform/lib/index.js:100:9
      at /Users/hsiliev/workspace/cf-abacus/node_modules/abacus-request/lib/index.js:331:18
      at /Users/hsiliev/workspace/cf-abacus/node_modules/abacus-transform/lib/index.js:85:5
      at _.map._.collect (/Users/hsiliev/workspace/cf-abacus/node_modules/underscore/underscore.js:172:24)
      at Function.cbmap [as map] (/Users/hsiliev/workspace/cf-abacus/node_modules/abacus-transform/lib/index.js:83:3)
      at /Users/hsiliev/workspace/cf-abacus/node_modules/abacus-request/lib/index.js:324:19
      at /Users/hsiliev/workspace/cf-abacus/node_modules/abacus-transform/lib/index.js:100:9
      at /Users/hsiliev/workspace/cf-abacus/node_modules/abacus-request/lib/index.js:303:13
      at Request._callback (/Users/hsiliev/workspace/cf-abacus/node_modules/abacus-request/lib/index.js:173:14)
      at Request.self.callback (/Users/hsiliev/workspace/cf-abacus/node_modules/request/request.js:187:22)
      at Request.<anonymous> (/Users/hsiliev/workspace/cf-abacus/node_modules/request/request.js:1044:10)
      at IncomingMessage.<anonymous> (/Users/hsiliev/workspace/cf-abacus/node_modules/request/request.js:965:12)
      at endReadableNT (_stream_readable.js:975:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by hsiliev** [comment]
Seems that we have too many connections to MongoDB and this causes it to hit the configured OS limits:
```
2016-08-31T11:12:16.433+0300 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:52341 #2033 (2033 connections now open)
2016-08-31T11:12:16.433+0300 I NETWORK  [initandlisten] failed to create thread after accepting new connection, closing connection
```

**Comment by hsiliev** [comment]
We can:
* reduce the search range in dataflow
* work on mongoclient to close DB connections

I personally prefer the first approach since mongoclient has no clean way to know when a DB connection can be closed.

**Comment by hsiliev** [comment]
To fix the issue I'm going to:
* allow end-date to be provided by the client
* restrict the time window: end - beginning =< month + slackWindow

This should result in 2-3 connections per error list request.
