### ISSUE TITLE
Dupe test fails

### ISSUE THREAD

**Issue by hsiliev** [cloudfoundry-incubator/cf-abacus#465]
Dupe test fails with:
```bash
npm start

npm run dupe -- -d 60000

> cf-abacus@0.0.6-dev.8 dupe /workspace/Develop/cf-abacus
> bin/dupe "-d" "60000"


> abacus-dupe-test@0.0.6-dev.8 dupe /workspace/Develop/cf-abacus/node_modules/abacus-dupe-test
> mocha --command "-d" "60000"

Testing...


  abacus-dupe
Posting document 1
Retrieving Usage Report
Setting report
Waiting 60000  milliseconds before submitting
Posting document 2
    1) submits usage for a sample resource and retrieves an aggregated usage report


  0 passing (1m)
  1 failing

  1) abacus-dupe submits usage for a sample resource and retrieves an aggregated usage report:

      Uncaught AssertionError: expected 409 to equal 201
      + expected - actual

      -409
      +201
      
      at lib/test/test.js:141:39
      at Request._callback (/workspace/Develop/cf-abacus/node_modules/abacus-request/lib/index.js:173:14)
      at Request.self.callback (/workspace/Develop/cf-abacus/node_modules/request/request.js:186:22)
      at Request.<anonymous> (/workspace/Develop/cf-abacus/node_modules/request/request.js:1081:10)
      at IncomingMessage.<anonymous> (/workspace/Develop/cf-abacus/node_modules/request/request.js:1001:12)
      at endReadableNT (_stream_readable.js:934:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

```

Dupe test is currently not part of [citest script](https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/bin/citest), therefore it is not executed when validating changes in Abacus.

**Comment by KRuelY** [comment]
I checked the docs that are submitted in the test

Doc 1 and doc 2 are exactly the same, so abacus throws 409 (Which is good). It seems that the test itself is wrong because it is not modifying the usage submitted after successful post.
