### ISSUE TITLE
Build loop with node5 and node7

### ISSUE THREAD

**Issue by charyorde** [cloudfoundry-incubator/cf-abacus#534]
Build took over 12 hours before failing with the following error output:
```
> babel

src/index.js -> lib/index.js
src/test/test.js -> lib/test/test.js

> lib/utils/urienv: npm run babel
< lib/utils/urienv: npm run babel

> abacus-urienv@0.0.6-dev.8 babel ~/cf-abacus/lib/utils/urienv
> babel

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn ~/cf-abacus/node_modules/abacus-babel/node_modules/.bin/babel EAGAIN
    at exports._errnoException (util.js:893:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:148:18)
    at node.js:405:3

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node@5/5.12.0_1/bin/node" "/usr/local/bin/npm" "run" "babel"
npm ERR! node v5.12.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! abacus-urienv@0.0.6-dev.8 babel: `babel`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the abacus-urienv@0.0.6-dev.8 babel script 'babel'.
```

**Comment by hsiliev** [comment]
Build is also looping with node 7

**Comment by rajkiranrbala** [comment]
I guess I have this problem with npm version 4.2. I am not sure if it has to do anything with the node version

**Comment by hsiliev** [comment]
The problem seems to be that publish is now split in two and one of the scripts clash with our "prepare": https://iamakulov.com/notes/all/npm-4-prepublish/

We need to change "prepare" to something else.
