### ISSUE TITLE
Abacus replay fails due to missing token

### ISSUE THREAD

**Issue by hsiliev** [cloudfoundry-incubator/cf-abacus#566]
Replay fails with:
```
2017-03-08T10:11:36.38+0200 [APP/PROC/WEB/0]OUT 2017-03-08T08:11:36.384Z e-abacus-oauth 52 Exception when checking authorization, { message: 'Cannot read property \'replace\' of undefined' } - TypeError: Cannot read property 'replace' of undefined
2017-03-08T10:11:36.38+0200 [APP/PROC/WEB/0]OUT     at Object.authorize (/home/vcap/app/node_modules/abacus-oauth/lib/index.js:161:26)
2017-03-08T10:11:36.38+0200 [APP/PROC/WEB/0]OUT     at Function.play$ (/home/vcap/app/node_modules/abacus-dataflow/lib/index.js:1495:41)
2017-03-08T10:11:36.38+0200 [APP/PROC/WEB/0]OUT     at tryCatch (/home/vcap/app/node_modules/regenerator-runtime/runtime.js:64:40)
2017-03-08T10:11:36.38+0200 [APP/PROC/WEB/0]OUT     at Generator.invoke [as _invoke] (/home/vcap/app/node_modules/regenerator-runtime/runtime.js:299:22)
2017-03-08T10:11:36.38+0200 [APP/PROC/WEB/0]OUT     at Generator.prototype.(anonymous function) [as next] (/home/vcap/app/node_modules/regenerator-runtime/runtime.js:116:21)
2017-03-08T10:11:36.38+0200 [APP/PROC/WEB/0]OUT     at next (/home/vcap/app/node_modules/co/index.js:74:21)
2017-03-08T10:11:36.38+0200 [APP/PROC/WEB/0]OUT     at /home/vcap/app/node_modules/co/index.js:45:5
2017-03-08T10:11:36.38+0200 [APP/PROC/WEB/0]OUT     at next (/home/vcap/app/node_modules/co/index.js:90:21)
2017-03-08T10:11:36.38+0200 [APP/PROC/WEB/0]OUT     at /home/vcap/app/node_modules/co/index.js:93:18
2017-03-08T10:11:36.38+0200 [APP/PROC/WEB/0]OUT     at Immediate.<anonymous> (/home/vcap/app/node_modules/co/index.js:52:14)
2017-03-08T10:11:36.38+0200 [APP/PROC/WEB/0]OUT     at runCallback (timers.js:637:20)
2017-03-08T10:11:36.38+0200 [APP/PROC/WEB/0]OUT     at tryOnImmediate (timers.js:610:5)
2017-03-08T10:11:36.38+0200 [APP/PROC/WEB/0]OUT     at processImmediate [as _immediateCallback] (timers.js:582:5)
2017-03-08T10:11:36.38+0200 [APP/PROC/WEB/0]OUT 2017-03-08T08:11:36.385Z e-abacus-dataflow 52 Error replaying input docs { statusCode: 401,
2017-03-08T10:11:36.38+0200 [APP/PROC/WEB/0]OUT   header: { 'WWW-Authenticate': 'Bearer realm="cf", error="invalid_token", error_description="malformed"' } }
```

**Comment by hsiliev** [comment]
The problem seems to be caused by missing request (and therefore authorization header) when `replay` calls `play` with request set to `undefined`.

Replay call:
https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/utils/dataflow/src/index.js#L1276-L1277

Play impl:
https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/utils/dataflow/src/index.js#L534-L550
