### ISSUE TITLE
Random unit test failures at usage aggregator - expected aggregated value is not matching the processed aggregated value

### ISSUE THREAD

**Issue by sasrin** [cloudfoundry-incubator/cf-abacus#64]
abacus-usage-aggregator
    ✓ constructs aggregated usage for an organization
    1) aggregates usage for an organization

  1 passing (1s)
  1 failing

  1) abacus-usage-aggregator aggregates usage for an organization:

      Uncaught AssertionError: expected { Object (organization_id, resources, ...) } to deeply equal { Object (organization_id, start, ...) }
      + expected - actual

                 "quantity": [
                   2
                   2
                   2
      -            24
      -            24
      -            24
      -            24
      +            32
      +            32
      +            32
      +            32
                 ]
               }
               {
                 "metric": "memory"
                     "consuming": 2
                     "since": 1420249000000
                   }
                   {
      -              "consumed": 26800000
      -              "consuming": 3
      +              "consumed": 32800000
      +              "consuming": 6
                     "since": 1420249000000
                   }
                   {
      -              "consumed": 26800000
      -              "consuming": 3
      +              "consumed": 32800000
      +              "consuming": 6
                     "since": 1420249000000
                   }
                   {
      -              "consumed": 26800000
      -              "consuming": 3
      +              "consumed": 32800000
      +              "consuming": 6
                     "since": 1420249000000
                   }
                   {
      -              "consumed": 26800000
      -              "consuming": 3
      +              "consumed": 32800000
      +              "consuming": 6
                     "since": 1420249000000
                   }
                 ]
               }
                     "quantity": [
                       2
                       2
                       2
      -                24
      -                24
      -                24
      -                24
      +                32
      +                32
      +                32
      +                32
                     ]
                   }
                   {
                     "metric": "memory"
                         "consuming": 2
                         "since": 1420249000000
                       }
                       {
      -                  "consumed": 26800000
      -                  "consuming": 3
      +                  "consumed": 32800000
      +                  "consuming": 6
                         "since": 1420249000000
                       }
                       {
      -                  "consumed": 26800000
      -                  "consuming": 3
      +                  "consumed": 32800000
      +                  "consuming": 6
                         "since": 1420249000000
                       }
                       {
      -                  "consumed": 26800000
      -                  "consuming": 3
      +                  "consumed": 32800000
      +                  "consuming": 6
                         "since": 1420249000000
                       }
                       {
      -                  "consumed": 26800000
      -                  "consuming": 3
      +                  "consumed": 32800000
      +                  "consuming": 6
                         "since": 1420249000000
                       }
                     ]
                   }
                         "quantity": [
                           2
                           2
                           2
      -                    24
      -                    24
      -                    24
      -                    24
      +                    32
      +                    32
      +                    32
      +                    32
                         ]
                       }
                       {
                         "metric": "memory"
                             "consuming": 2
                             "since": 1420249000000
                           }
                           {
      -                      "consumed": 26800000
      -                      "consuming": 3
      +                      "consumed": 32800000
      +                      "consuming": 6
                             "since": 1420249000000
                           }
                           {
      -                      "consumed": 26800000
      -                      "consuming": 3
      +                      "consumed": 32800000
      +                      "consuming": 6
                             "since": 1420249000000
                           }
                           {
      -                      "consumed": 26800000
      -                      "consuming": 3
      +                      "consumed": 32800000
      +                      "consuming": 6
                             "since": 1420249000000
                           }
                           {
      -                      "consumed": 26800000
      -                      "consuming": 3
      +                      "consumed": 32800000
      +                      "consuming": 6
                             "since": 1420249000000
                           }
                         ]
                       }
                             "quantity": [
                               2
                               2
                               2
      -                        24
      -                        24
      -                        24
      -                        24
      +                        32
      +                        32
      +                        32
      +                        32
                             ]
                           }
                           {
                             "metric": "memory"
                                 "consuming": 2
                                 "since": 1420249000000
                               }
                               {
      -                          "consumed": 26800000
      -                          "consuming": 3
      +                          "consumed": 32800000
      +                          "consuming": 6
                                 "since": 1420249000000
                               }
                               {
      -                          "consumed": 26800000
      -                          "consuming": 3
      +                          "consumed": 32800000
      +                          "consuming": 6
                                 "since": 1420249000000
                               }
                               {
      -                          "consumed": 26800000
      -                          "consuming": 3
      +                          "consumed": 32800000
      +                          "consuming": 6
                                 "since": 1420249000000
                               }
                               {
      -                          "consumed": 26800000
      -                          "consuming": 3
      +                          "consumed": 32800000
      +                          "consuming": 6
                                 "since": 1420249000000
                               }
                             ]
                           }
                     "quantity": [
                       2
                       2
                       2
      -                24
      -                24
      -                24
      -                24
      +                32
      +                32
      +                32
      +                32
                     ]
                   }
                   {
                     "metric": "memory"
                         "consuming": 2
                         "since": 1420249000000
                       }
                       {
      -                  "consumed": 26800000
      -                  "consuming": 3
      +                  "consumed": 32800000
      +                  "consuming": 6
                         "since": 1420249000000
                       }
                       {
      -                  "consumed": 26800000
      -                  "consuming": 3
      +                  "consumed": 32800000
      +                  "consuming": 6
                         "since": 1420249000000
                       }
                       {
      -                  "consumed": 26800000
      -                  "consuming": 3
      +                  "consumed": 32800000
      +                  "consuming": 6
                         "since": 1420249000000
                       }
                       {
      -                  "consumed": 26800000
      -                  "consuming": 3
      +                  "consumed": 32800000
      +                  "consuming": 6
                         "since": 1420249000000
                       }
                     ]
                   }
                         "quantity": [
                           2
                           2
                           2
      -                    24
      -                    24
      -                    24
      -                    24
      +                    32
      +                    32
      +                    32
      +                    32
                         ]
                       }
                       {
                         "metric": "memory"
                             "consuming": 2
                             "since": 1420249000000
                           }
                           {
      -                      "consumed": 26800000
      -                      "consuming": 3
      +                      "consumed": 32800000
      +                      "consuming": 6
                             "since": 1420249000000
                           }
                           {
      -                      "consumed": 26800000
      -                      "consuming": 3
      +                      "consumed": 32800000
      +                      "consuming": 6
                             "since": 1420249000000
                           }
                           {
      -                      "consumed": 26800000
      -                      "consuming": 3
      +                      "consumed": 32800000
      +                      "consuming": 6
                             "since": 1420249000000
                           }
                           {
      -                      "consumed": 26800000
      -                      "consuming": 3
      +                      "consumed": 32800000
      +                      "consuming": 6
                             "since": 1420249000000
                           }
                         ]
                       }
      
      at Assertion.assertEqual (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-mocha/node_modules/chai/lib/chai/core/assertions.js:455:19)
      at Assertion.ctx.(anonymous function) [as equal] (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-mocha/node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at lib/test/test.js:1617:76
      at /home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-batch/lib/index.js:28:349
      at _.map._.collect (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/underscore/underscore.js:172:24)
      at /home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-batch/lib/index.js:28:215
      at /home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-request/lib/index.js:64:293
      at /home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-transform/lib/index.js:37:543
      at /home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-request/lib/index.js:62:616
      at /home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-transform/lib/index.js:34:222
      at _.map._.collect (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/underscore/underscore.js:172:24)
      at Function.cbmap [as map] (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-transform/lib/index.js:34:48)
      at /home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-request/lib/index.js:62:80
      at /home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-transform/lib/index.js:37:543
      at Object.callback (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-request/lib/index.js:61:359)
      at Request._callback (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-request/lib/index.js:44:351)
      at Request.self.callback (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-request/node_modules/request/request.js:198:22)
      at Request.<anonymous> (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-request/node_modules/request/request.js:1063:14)
      at IncomingMessage.<anonymous> (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-request/node_modules/request/request.js:1009:12)
      at _stream_readable.js:944:16

**Comment by sasrin** [comment]
Another variation:

[0m  abacus-usage-aggregator[0m

  [32m  âœ“[0m[90m constructs aggregated usage for an organization[0m

  [31m  1) aggregates usage for an organization[0m


[92m [0m[32m 1 passing[0m[90m (2s)[0m
[31m  1 failing[0m

[0m  1) abacus-usage-aggregator aggregates usage for an organization:

      [31mUncaught AssertionError: expected { Object (organization_id, resources, ...) } to deeply equal { Object (organization_id, start, ...) }[0m
      [32m+ expected[0m [31m- actual[0m

                 "quantity": [
                   2
                   2
                   2
      [31m-            2[0m
      [31m-            2[0m
      [31m-            2[0m
      [31m-            2[0m
      [32m+            32[0m
      [32m+            32[0m
      [32m+            32[0m
      [32m+            32[0m
                 ]
               }
               {
                 "metric": "memory"
                     "consuming": 2
                     "since": 1420249000000
                   }
                   {
      [31m-              "consumed": 0[0m
      [31m-              "consuming": -1[0m
      [32m+              "consumed": 32800000[0m
      [32m+              "consuming": 6[0m
                     "since": 1420249000000
                   }
                   {
      [31m-              "consumed": 0[0m
      [31m-              "consuming": -1[0m
      [32m+              "consumed": 32800000[0m
      [32m+              "consuming": 6[0m
                     "since": 1420249000000
                   }
                   {
      [31m-              "consumed": 0[0m
      [31m-              "consuming": -1[0m
      [32m+              "consumed": 32800000[0m
      [32m+              "consuming": 6[0m
                     "since": 1420249000000
                   }
                   {
      [31m-              "consumed": 0[0m
      [31m-              "consuming": -1[0m
      [32m+              "consumed": 32800000[0m
      [32m+              "consuming": 6[0m
                     "since": 1420249000000
                   }
                 ]
               }
                     "quantity": [
                       2
                       2
                       2
      [31m-                2[0m
      [31m-                2[0m
      [31m-                2[0m
      [31m-                2[0m
      [32m+                32[0m
      [32m+                32[0m
      [32m+                32[0m
      [32m+                32[0m
                     ]
                   }
                   {
                     "metric": "memory"
                         "consuming": 2
                         "since": 1420249000000
                       }
                       {
      [31m-                  "consumed": 0[0m
      [31m-                  "consuming": -1[0m
      [32m+                  "consumed": 32800000[0m
      [32m+                  "consuming": 6[0m
                         "since": 1420249000000
                       }
                       {
      [31m-                  "consumed": 0[0m
      [31m-                  "consuming": -1[0m
      [32m+                  "consumed": 32800000[0m
      [32m+                  "consuming": 6[0m
                         "since": 1420249000000
                       }
                       {
      [31m-                  "consumed": 0[0m
      [31m-                  "consuming": -1[0m
      [32m+                  "consumed": 32800000[0m
      [32m+                  "consuming": 6[0m
                         "since": 1420249000000
                       }
                       {
      [31m-                  "consumed": 0[0m
      [31m-                  "consuming": -1[0m
      [32m+                  "consumed": 32800000[0m
      [32m+                  "consuming": 6[0m
                         "since": 1420249000000
                       }
                     ]
                   }
                         "quantity": [
                           2
                           2
                           2
      [31m-                    2[0m
      [31m-                    2[0m
      [31m-                    2[0m
      [31m-                    2[0m
      [32m+                    32[0m
      [32m+                    32[0m
      [32m+                    32[0m
      [32m+                    32[0m
                         ]
                       }
                       {
                         "metric": "memory"
                             "consuming": 2
                             "since": 1420249000000
                           }
                           {
      [31m-                      "consumed": 0[0m
      [31m-                      "consuming": -1[0m
      [32m+                      "consumed": 32800000[0m
      [32m+                      "consuming": 6[0m
                             "since": 1420249000000
                           }
                           {
      [31m-                      "consumed": 0[0m
      [31m-                      "consuming": -1[0m
      [32m+                      "consumed": 32800000[0m
      [32m+                      "consuming": 6[0m
                             "since": 1420249000000
                           }
                           {
      [31m-                      "consumed": 0[0m
      [31m-                      "consuming": -1[0m
      [32m+                      "consumed": 32800000[0m
      [32m+                      "consuming": 6[0m
                             "since": 1420249000000
                           }
                           {
      [31m-                      "consumed": 0[0m
      [31m-                      "consuming": -1[0m
      [32m+                      "consumed": 32800000[0m
      [32m+                      "consuming": 6[0m
                             "since": 1420249000000
                           }
                         ]
                       }
                             "quantity": [
                               2
                               2
                               2
      [31m-                        2[0m
      [31m-                        2[0m
      [31m-                        2[0m
      [31m-                        2[0m
      [32m+                        32[0m
      [32m+                        32[0m
      [32m+                        32[0m
      [32m+                        32[0m
                             ]
                           }
                           {
                             "metric": "memory"
                                 "consuming": 2
                                 "since": 1420249000000
                               }
                               {
      [31m-                          "consumed": 0[0m
      [31m-                          "consuming": -1[0m
      [32m+                          "consumed": 32800000[0m
      [32m+                          "consuming": 6[0m
                                 "since": 1420249000000
                               }
                               {
      [31m-                          "consumed": 0[0m
      [31m-                          "consuming": -1[0m
      [32m+                          "consumed": 32800000[0m
      [32m+                          "consuming": 6[0m
                                 "since": 1420249000000
                               }
                               {
      [31m-                          "consumed": 0[0m
      [31m-                          "consuming": -1[0m
      [32m+                          "consumed": 32800000[0m
      [32m+                          "consuming": 6[0m
                                 "since": 1420249000000
                               }
                               {
      [31m-                          "consumed": 0[0m
      [31m-                          "consuming": -1[0m
      [32m+                          "consumed": 32800000[0m
      [32m+                          "consuming": 6[0m
                                 "since": 1420249000000
                               }
                             ]
                           }
                     "quantity": [
                       2
                       2
                       2
      [31m-                2[0m
      [31m-                2[0m
      [31m-                2[0m
      [31m-                2[0m
      [32m+                32[0m
      [32m+                32[0m
      [32m+                32[0m
      [32m+                32[0m
                     ]
                   }
                   {
                     "metric": "memory"
                         "consuming": 2
                         "since": 1420249000000
                       }
                       {
      [31m-                  "consumed": 0[0m
      [31m-                  "consuming": -1[0m
      [32m+                  "consumed": 32800000[0m
      [32m+                  "consuming": 6[0m
                         "since": 1420249000000
                       }
                       {
      [31m-                  "consumed": 0[0m
      [31m-                  "consuming": -1[0m
      [32m+                  "consumed": 32800000[0m
      [32m+                  "consuming": 6[0m
                         "since": 1420249000000
                       }
                       {
      [31m-                  "consumed": 0[0m
      [31m-                  "consuming": -1[0m
      [32m+                  "consumed": 32800000[0m
      [32m+                  "consuming": 6[0m
                         "since": 1420249000000
                       }
                       {
      [31m-                  "consumed": 0[0m
      [31m-                  "consuming": -1[0m
      [32m+                  "consumed": 32800000[0m
      [32m+                  "consuming": 6[0m
                         "since": 1420249000000
                       }
                     ]
                   }
                         "quantity": [
                           2
                           2
                           2
      [31m-                    2[0m
      [31m-                    2[0m
      [31m-                    2[0m
      [31m-                    2[0m
      [32m+                    32[0m
      [32m+                    32[0m
      [32m+                    32[0m
      [32m+                    32[0m
                         ]
                       }
                       {
                         "metric": "memory"
                             "consuming": 2
                             "since": 1420249000000
                           }
                           {
      [31m-                      "consumed": 0[0m
      [31m-                      "consuming": -1[0m
      [32m+                      "consumed": 32800000[0m
      [32m+                      "consuming": 6[0m
                             "since": 1420249000000
                           }
                           {
      [31m-                      "consumed": 0[0m
      [31m-                      "consuming": -1[0m
      [32m+                      "consumed": 32800000[0m
      [32m+                      "consuming": 6[0m
                             "since": 1420249000000
                           }
                           {
      [31m-                      "consumed": 0[0m
      [31m-                      "consuming": -1[0m
      [32m+                      "consumed": 32800000[0m
      [32m+                      "consuming": 6[0m
                             "since": 1420249000000
                           }
                           {
      [31m-                      "consumed": 0[0m
      [31m-                      "consuming": -1[0m
      [32m+                      "consumed": 32800000[0m
      [32m+                      "consuming": 6[0m
                             "since": 1420249000000
                           }
                         ]
                       }
      [0m[90m
      at Assertion.assertEqual (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-mocha/node_modules/chai/lib/chai/core/assertions.js:455:19)
      at Assertion.ctx.(anonymous function) [as equal] (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-mocha/node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at lib/test/test.js:1617:76
      at /home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-batch/lib/index.js:28:349
      at _.map._.collect (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/underscore/underscore.js:172:24)
      at /home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-batch/lib/index.js:28:215npm ERR! Test failed.  See above for more details.
