### ISSUE TITLE
Demo client fails to run at Travis

### ISSUE THREAD

**Issue by sasrin** [cloudfoundry-incubator/cf-abacus#68]
```
  ✓ submits usage for a sample resource and retrieves an aggregated usage report (8625ms)
Processed NaN usage docs
```
```
 1) submits usage for a sample resource and retrieves an aggregated usage report
  1 passing (9s)
  1 failing
  1) abacus-demo-client submits usage for a sample resource and retrieves an aggregated usage report:
     Error: done() called multiple times
      at Suite.<anonymous> (lib/test/test.js:31:3)
      at Object.<anonymous> (lib/test/test.js:30:1)
      at Array.forEach (native)
      at Object.runCLI (/Users/travis/build/sasrin/cf-abacus/node_modules/abacus-mocha/src/index.js:197:9)
      at Object.<anonymous> (/Users/travis/build/sasrin/cf-abacus/node_modules/abacus-mocha/mocha:5:27)
      at node.js:951:3
```

**Comment by jsdelfino** [comment]
I'm seeing that error too.
