### ISSUE TITLE
Provisioning stub unit test case is not executing all tests

### ISSUE THREAD

**Issue by sasrin** [cloudfoundry-incubator/cf-abacus#79]
The following line 

https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/stubs/provisioning/src/test/test.js#L52

completes the test before executing

  https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/stubs/provisioning/src/test/test.js#L73

Also we are testing 404 as an error, rather than a valid response with statusCode 404.

```
expect(err).to.not.equal(undefined);
expect(err.statusCode).to.equal(404);
```

**Comment by sasrin** [comment]
After changing the test code to validate the response with statusCode 404, found that we are getting 200 for an invalid resource id. @jsdelfino what is the expected behavior here? I believe the design is to get 404 not 200.

```
-          expect(err).to.not.equal(undefined);
-          expect(err.statusCode).to.equal(404);
-          done();
+          expect(err).to.equal(undefined);
+          expect(val.statusCode).to.equal(404);
```
 1) abacus-provisioning-stub returns resource instance info by region/org/space/app/resource/plan/instance:

      Uncaught AssertionError: expected 200 to equal 404
      + expected - actual

      -200
      +404
      
      at Object.callback (lib/test/test.js:75:33)
      at Request._callback (node_modules/abacus-request/lib/index.js:44:351)
      at Request.self.callback (node_modules/abacus-request/node_modules/request/request.js:198:22)
      at Request.<anonymous> (node_modules/abacus-request/node_modules/request/request.js:1063:14)
      at IncomingMessage.<anonymous> (node_modules/abacus-request/node_modules/request/request.js:1009:12)
      at _stream_readable.js:908:16

**Comment by sasrin** [comment]
Found the bug at 

https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/stubs/provisioning/src/index.js#L127

Since config is now an async, we need to yield before responding back to the request. After that we should get expected 404.
