### ISSUE TITLE
EventEmitter memory leak warning fills up the travis build log

### ISSUE THREAD

**Issue by sasrin** [cloudfoundry-incubator/cf-abacus#82]
```
(node) warning: possible EventEmitter memory leak detected. 11 finish listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at ServerResponse.addListener (events.js:239:17)
    at ServerResponse.res.on (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-express/node_modules/compression/index.js:119:19)
    at /home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-express/lib/index.js:306:9
    at Layer.handle [as handle_request] (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:312:13)
    at /home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:330:12)
    at next (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:271:10)
    at /home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-express/lib/index.js:333:5
    at Layer.handle [as handle_request] (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:312:13)
    at /home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:330:12)
    at next (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:271:10)
    at expressInit (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-express/node_modules/express/lib/middleware/init.js:33:5)
    at Layer.handle [as handle_request] (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:312:13)
    at /home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:330:12)
    at next (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:271:10)
    at query (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-express/node_modules/express/lib/middleware/query.js:49:5)
    at Layer.handle [as handle_request] (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:312:13)
    at /home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:330:12)
    at next (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/index.js:176:3)
    at EventEmitter.handle (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-express/node_modules/express/lib/application.js:173:10)
    at app (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-express/node_modules/express/lib/express.js:38:9)
    at /home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-router/lib/index.js:188:7
(node) warning: possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at ServerResponse.addListener (events.js:239:17)
    at ServerResponse.res.on (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-express/node_modules/compression/index.js:119:19)
    at /home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-express/lib/index.js:307:9
    at Layer.handle [as handle_request] (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-express/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/travis/build/cloudfoundry-incu
```

**Comment by sasrin** [comment]
After checking in this change, travis build ran into following errors:

- node version 0.12.7

```
Processed 116 usage docs for org7
Processed 116 usage docs for org8
Processed 117 usage docs for org9
Processed 117 usage docs for org10
Processed 117 usage docs for org11
Processed 117 usage docs for org12

assert.js:86
  throw new assert.AssertionError({
        ^
AssertionError: Resource leak detected.
    at removeWorker (cluster.js:346:9)
    at ChildProcess.<anonymous> (cluster.js:366:34)
    at ChildProcess.g (events.js:199:16)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)

ERR![0m[35m[0m Linux 2.6.32-042stab108.8
ERR![0m [0m[35margv[0m "/home/travis/.nvm/versions/node/v0.12.7/bin/node" "/home/travis/.nvm/versions/node/v0.12.7/bin/npm" "start"
ERR![0m [0m[35mnode[0m v0.12.7
ERR![0m [0m[35mnpm [0m v2.11.3
ERR![0m [0m[35mcode[0m ELIFECYCLE
ERR![0m[35m[0m abacus-dbserver@0.0.1-dev.3 start: `./dbserver start`
ERR![0m[35m[0m Exit status 1
ERR![0m[35m[0m 
ERR![0m[35m[0m Failed at the abacus-dbserver@0.0.1-dev.3 start script './dbserver start'.
ERR![0m[35m[0m This is most likely a problem with the abacus-dbserver package,
```

- node version 0.10.40 does not support  `EventEmitter.defaultMaxListeners`

**Comment by sasrin** [comment]
So need to scale down performance test to avoid the above mentioned errors at Travis.
